apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambassador
  namespace: argocd
spec:
  destination:
    namespace: ambassador
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: edge-stack
    helm:
      releaseName: edge-stack
    repoURL: https://app.getambassador.io
    targetRevision: 8.3.0
  syncPolicy:
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true