---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: echo-host
  namespace: ambassador
spec:
  hostname: echo.wounn.xyz
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: admin@wounn.xyz
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: argo-host
  namespace: ambassador
spec:
  hostname: argo.wounn.xyz
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: admin@wounn.xyz
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: whoami-host
  namespace: ambassador
spec:
  hostname: whoami.wounn.xyz
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: admin@wounn.xyz
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: gitea-host
  namespace: ambassador
spec:
  hostname: git.wounn.xyz
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: admin@wounn.xyz
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080