apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: argocd
spec:
  host: argo.wounn.xyz
  prefix: /
  service: argocd-server:443

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: whoami-server-ui
  namespace: whoami
spec:
  host: whoami.wounn.xyz
  prefix: /
  service: whoami:80

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: gitea-server-ui
  namespace: gitea
spec:
  host: git.wounn.xyz
  prefix: /
  service: gitea-http:3000